routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

Route::get('/', function () {
    return view('welcome');
});
Route::resource('user',UserController::class);

app/Models/User.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
class User extends Model
{
    protected $table = 'user';
	protected $primaryKey = 'id';
	static $rules = ['nama' => 'required', 'email' => 'required','foto'=>'required|image|mimes:jpeg,png,jpg,gif,svg|max:16384'];
	protected $perPage = 20;
	protected $fillable = ['nama','foto','email','job','password'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user=User::first()->paginate(20);
		return view('user.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User();
		return view('user.create', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        	//cek validasi
		request()->validate(User::$rules);
		//mulai transaksi
		\DB::beginTransaction();
		try
		{
      $tujuan_upload = 'foto';
      //simpan ke tabel kota
      \DB::table('user')->insert(['nama'=>$request->nama,
										'foto'=>$request->foto->move($tujuan_upload, $request->foto->getClientOriginalName()),
										'email'=>$request->email,
                    'job'=>$request->job,
                    'password'=>$request->password]);										
			//jika tidak ada kesalahan commit/simpan
			\DB::commit();
			return redirect()->route('user.index')->with('success', 'user created successfully.');
		} 
		catch (\Throwable $e) 
		{
			//jika terjadi kesalahan batalkan semua
			\DB::rollback();
			return redirect()->route('user.index')->with('success', 'Penyimpanan dibatalkan semua, ada kesalahan......');
		}
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user =User::find($id);
		return view('user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user =User::find($id);
		return view('user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate(User::$rules);
        $tujuan_upload = 'foto';
		//mulai transaksi
		\DB::beginTransaction();
		try
		{
			\DB::table('user')->where('id',$id)->update(['nama'=>$request->nama,
														'foto'=>$request->foto->move($tujuan_upload, $request->foto->getClientOriginalName()),
														'email'=>$request->email,
														'job'=>$request->job,'password'=>$request->password]);
			//$user->update($request->all());
			\DB::commit();
			return redirect()->route('user.index')->with('success', 'User updated successfully');
		}
		catch (\Throwable $e) 
		{
			//jika terjadi kesalahan batalkan semua
			\DB::rollback();
			return redirect()->route('user.index')->with('success', 'User Batal diubah, ada kesalahan');
		} 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       //mulai transaksi
		\DB::beginTransaction();
		try
		{
			//hapus rekaman tabel kota
			$user =User::find($id)->delete();
			\DB::commit();
			return redirect()->route('user.index')->with('success', 'user deleted successfully');
		} 
		catch (\Throwable $e) 
		{
			//jika terjadi kesalahan batalkan semua
			\DB::rollback();
			return redirect()->route('user.index')->with('success', 'user ada kesalahan hapus batal... ');
		}
    }
}

resources/views/app.blade.php
<!DOCTYPE html> <html lang="en"> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge"> 
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"> 
<title></title>
 <style> .martop-sm {margin-top: 15px;} .martop-lg {margin-top: 70px;} </style>
 </head> 
 <body>
      <div class="container martop-lg"> 
          <div class="panel panel-default"> 
              <div class="panel-body">@yield('content')</div> 
          </div> 
      </div>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </body>
</html>

resources/views/user/create.blade.php
@extends('app')
@section('title', 'User')
@section('content_header')
 <h2>User/h2>
@stop
@section('content')
 <section class="content container-fluid">
 <div class="row">
 <div class="col-md-12">
 @includeif('partials.errors')
 <div class="card card-default">
 <div class="card-header">
 <span class="card-title"><h3>Tambah User</h3></span>
 </div>
<div class="card-body">
 <form method="POST" action="{{ route('user.store') }}"role="form" enctype="multipart/form-data">
 @csrf
 @include('user.form')
 </form>
 </div>
 </div>
 </div>
 </div>
 </section>
@endsection

resources/views/user/edit.blade.php
@extends('app')
@section('title', 'User')
@section('content_header')
 <h2>User</h2>
@stop
@section('content')
<section class="content container-fluid">
 <div class="row">
 <div class="col-md-12">
 @includeif('partials.errors')
 <div class="card card-default">
 <div class="card-header">
 <span class="card-title"><h3>Mengubah Data User </h3></span>
 </div>
 <div class="card-body">
 <form method="POST" action="{{ route('user.update',$user->id) }}" role="form" enctype="multipart/form-data">
 {{ method_field('PATCH') }}
 @csrf
 @method('PUT')
                <div class="form-group">
                    <label for="nama">Nama</label>                    
                    <input type="text" name="nama" class="form-control" id="nama" value="{{ $user->nama }}" aria-describedby="nama" >                
                </div>
                <div class="form-group">
                    <label for="email">Email</label>                    
                    <input type="text" name="email" class="form-control" id="email" value="{{ $user->email }}" aria-describedby="email" >                
                </div>
				<div class="form-group">
                    <label for="job">Job</label>                    
                    <input type="text" name="job" class="form-control" id="job" value="{{ $user->job }}" aria-describedby="job" >                
                </div>
                <div class="form-group">
                    <label for="writer">Password</label>                    
                    <input type="password" name="password" class="form-control" id="password" value="{{ $user->password }}" aria-describedby="password" >                
                </div>
				<div class="form-group">
                    <label for="foto">Foto</label>                    
                    <input type="file" name="foto" class="form-control" id="foto" value="{{ $user->foto }}" aria-describedby="foto" >                
                </div>
            <button type="submit" class="btn btn-primary">Submit</button>
 </form>
 </form>
 </div>
 </div>
 </div>
 </div>
 </section>
@endsection

resources/views/user/form.blade.php
<div class="box box-info padding-1">
 <div class="box-body">

 <div class="form-group">
 {{ Form::label('nama') }}
 {{ Form::text('nama', $user->nama, ['class' => 'form-control' . ($errors->has('nama') ? ' is-invalid' : ''), 'placeholder' => 'Nama']) }}
 {!! $errors->first('nama', '<div class="invalid-feedback">:message</p>') !!}
 </div></div>
 <div class="form-group">
 {{ Form::label('email') }}
 {{ Form::text('email', $user->email, ['class' => 'form-control' . ($errors->has('email') ? ' is-invalid' : ''), 'placeholder' => 'E-mail']) }}
 {!! $errors->first('email', '<div class="invalid-feedback">:message</p>') !!}
 </div></div>
 <div class="form-group">
 {{ Form::label('job') }}
 {{ Form::text('job', $user->job, ['class' => 'form-control' . ($errors->has('job') ? ' is-invalid' : ''), 'placeholder' => 'Job']) }}
 {!! $errors->first('job', '<div class="invalid-feedback">:message</p>') !!}
 </div></div>
 <div class="form-group">
 {{ Form::label('password') }}
 {{ Form::password('password', $user->password, ['class' => 'form-control' . ($errors->has('password') ? ' is-invalid' : ''), 'placeholder' => 'Password']) }}
 {!! $errors->first('password', '<div class="invalid-feedback">:message</p>') !!}
 </div></div>
  <div class="form-group">
 {{ Form::label('foto') }}
 {{ Form::file('foto', $user->foto, ['class' => 'form-control' . ($errors->has('foto') ? ' is-invalid' : ''), 'placeholder' => 'Foto']) }}
 {!! $errors->first('foto', '<div class="invalid-feedback">:message</p>') !!}
 </div></div>
 <div class="box-footer mt20">
 <button type="submit" class="btn btn-primary">Simpan</button>
</div>
</div>

resources/views/user/index.blade.php
@extends('app')
@section('title', 'User')

@section('content_header')
	<h2>Tabel User</h2>
@stop

@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<div class="card">
				<div class="card-header">
					<div style="display: flex; justify-content: spacebetween; align-items: center;">
						<span id="card_title">
							<h3> {{ __('User') }} </h3>
						</span>
						<div class="float-right">
							@include('user.search',['url'=>'user','link'=>'user'])
						</div>
					</div>
				</div>
				@if ($message = Session::get('success'))
				<div class="alert alert-success">
					<p>{{ $message }}</p>
				</div>
				@endif
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-striped table-hover">
							<thead class="thead">
								<tr>
									<th>Id</th>
									<th>Foto</th>
									<th>Nama</th>
									<th>E-Mail</th>
									<th>Job</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@foreach ($user as $usr)
								<tr>
								    <td>{{ $usr->id }}</td>
									<td><img src="{{ $usr -> foto }}" style="width: 50px; height: 50px; border-radius: 50%;" alt="foto"></td>
									<td>{{ $usr->nama }}</td>
									<td>{{ $usr->email }}</td>
									<td>{{ $usr->job }}</td>
									<td>
									<form action="{{ route('user.destroy',$usr->id) }}" method="POST">
										<a class="btn btn-sm btn-primary" href="{{ route('user.show',$usr->id) }}">
											<i class="fa fa-fw fa-eye"></i> Lihat</a>
										<a class="btn btn-sm btn-success" href="{{ route('user.edit',$usr->id) }}">
											<i class="fa fa-fw fa-edit"></i> Ubah</a>
											@csrf
											@method('DELETE')
											<button type="submit" class="btn btn-danger btn-sm">
											<i class="fa fa-fw fa-trash"></i> Hapus</button>
										</form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
			{!! $user ?? ''->links() !!}
		</div>
	</div>
 </div>
@endsection

resources/views/user/search.blade.php
{!! Form::open(['method'=>'GET','url'=>$url,'class'=>'navbar-form navbarleft','role'=>'search']) !!}
<div class="custom-search-form">
	<a href="{{ url($link.'/create') }}" class="btn btn-primary btnsm"><span class="glyphicon glyphicon-plus"></span> Tambah</a>
		<input type="text" class="form-control" name="search" placeholder="Search...">
		<button class="btn btn-default-sm" type="submit">
		Cari
	</span>
</div>
{!! Form::close() !!}

resources/views/user/show.blade.php
@extends('app') 
@section('title', 'User') 
@section('content_header') 
<h2> {{ $user->nama ?? 'Show User' }}</h2>
 @stop @section('content') 
 <section class="content container-fluid"> 
     <div class="row"> <div class="col-md-12"> 
         <div class="card"> 
             <div class="card-header"> 
                 <div class="float-left"> 
                     <span class="card-title">
                         <h3>Lihat User</h3>
                     </span> 
                 </div> 
                 <div class="float-right"> 
                     <a class="btn btn-primary" href="{{ route('user.index') }}"> Kembali</a> 
                </div> 
            </div> 
            <div class="card-body">
                <table width=80%>
                    <tr>
                <div class="form-group">
                    <td> 
                    <strong>Nama:</strong>
                    </td>
                    <td> {{ $user->nama }} </td>
                </div> 
                    </tr>
                    <tr>
                <div class="form-group">
                    <td> 
                    <strong>E-mail:</strong>
                    </td> 
                    <td>{{ $user->email }}</td> 
                </div>
                    </tr> 
                    <tr>
                <div class="form-group"> 
                    <td>
                    <strong>Job:</strong>
                    </td>
                    <td> {{ $user->job }}</td> 
                </div> 
                    </tr>
                    <tr>
                <div class="form-group">
                    <td> 
                    <strong>Foto: </strong>
                    <td><img src="{{ URL::to('/') }}/{{ $user -> foto }}" style="width: 100px; height: 100px;border-radius: 50%" alt="foto"> </td> 
                </div> 
                    </tr>
                </table>
            </div>
        </div> 
    </div> 
</div>
</section> 
@endsection